In [1]:
# we will need the credentials we saved in the .env file
from dotenv import dotenv_values

# We also will need SQLAlchemy and its functions
from sqlalchemy import create_engine, types
from sqlalchemy.dialects.postgresql import JSON as postgres_json

import pandas as pd

# requests library will make the API calls. 
# the json package will parse the JSON string and convert it to Python data structures
import requests
import json

# with 'datetime' we want to catch the timestamp of the API call. For the actuality reference. 
# and 'time' for slowing down a .bit
from datetime import datetime
import time

In [3]:
airport_staids = {
    'LAX': 72295 #Los Angeles International Airport
    ,'JFK': 71845 #John F. Kennedy International Airport New York
    ,'DEN': 72565 # Denver International Airport
    ,'DTW': 72537 # Detroit Metropolitan airport
    ,'ORD': 72530 #Chicago 
    ,'ATL': 72219 #Atlanta    
     }

In [5]:
# getting API and DB credentials - Alternative 1: dotenv_values()

config = dotenv_values()

api_key = config['x-rapidapi-key'] # align the key label with your .env file

In [19]:
first_days=pd.date_range(start='11/12/2022', end='31/01/2023', freq='MS')
last_days = first_days + pd.offsets.MonthEnd() # see, what we did here? DRY rules! :)
first_days_list = first_days.strftime('%Y-%m-%d').tolist()
last_days_list = last_days.astype(str).tolist()
print(first_days_list) 
print(last_days_list)
monthly_ranges = [(start_date, end_date) for start_date, end_date in zip(first_days_list, last_days_list)]

['2022-12-01', '2023-01-01']
['2022-12-31', '2023-01-31']

In [20]:
import time

for airport in airport_staids:
    print(airport)
    
    for onemonth in monthly_ranges:
    
        querystring = {
            "station":airport_staids[airport]
            ,"start": onemonth[0] # slice the start date from the iterator
            ,"end": onemonth[1] # slice the end date from the iterator
            ,"model":"true"
        }
         
        print(querystring) 
       
        time.sleep(0.34)
    print()

LAX
{'station': 72295, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72295, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

JFK
{'station': 71845, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 71845, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

DEN
{'station': 72565, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72565, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

DTW
{'station': 72537, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72537, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

ORD
{'station': 72530, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72530, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

ATL
{'station': 72219, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72219, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

In [21]:
#  let's catch each response in a dictionary. create an empty dictionary with the following keys:
weather_hourly_dict = {'extracted_at':[], 
                       'airport_code':[], 
                       'station_id':[], 
                       'extracted_data':[]}

# API CALL hourly (station) - for the syntax: see the rapidapi interface

url = "https://meteostat.p.rapidapi.com/stations/hourly"

headers = {
        "X-RapidAPI-Key": api_key,
        "X-RapidAPI-Host": "meteostat.p.rapidapi.com"
}


# double for-loop for the querystrings
for airport in airport_staids:
    
    # adding some logs
    print(airport) 
    
    for onemonth in monthly_ranges:
    
        querystring = {
            "station":airport_staids[airport]
            ,"start":onemonth[0]
            ,"end":onemonth[1]
            ,"model":"true"
        }
        
        # making one call with the current querystring
        response = requests.get(url, headers=headers, params=querystring)
        
        # adding some logs to catch errors
        if response.status_code != 200:
            print(f'status code {response.status_code} -> research error')
            print(querystring, end="\n\n")
        else:
            print(querystring)
        
        # appending data to the dictionary:
        weather_hourly_dict['extracted_at'].append(datetime.now())                # timestamp,
        weather_hourly_dict['airport_code'].append(airport)                       # airport code
        weather_hourly_dict['station_id'].append(airport_staids[airport])         # weater Station ID
        weather_hourly_dict['extracted_data'].append(json.loads(response.text))   # JSON string
        
        time.sleep(0.34)
        
    print()

LAX
{'station': 72295, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72295, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

JFK
{'station': 71845, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 71845, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

DEN
{'station': 72565, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72565, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

DTW
{'station': 72537, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72537, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

ORD
{'station': 72530, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72530, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

ATL
{'station': 72219, 'start': '2022-12-01', 'end': '2022-12-31', 'model': 'true'}
{'station': 72219, 'start': '2023-01-01', 'end': '2023-01-31', 'model': 'true'}

In [22]:
weather_hourly_dict

{'extracted_at': [datetime.datetime(2025, 7, 17, 10, 30, 15, 617482),
  datetime.datetime(2025, 7, 17, 10, 30, 17, 367580),
  datetime.datetime(2025, 7, 17, 10, 30, 18, 935360),
  datetime.datetime(2025, 7, 17, 10, 30, 20, 520268),
  datetime.datetime(2025, 7, 17, 10, 30, 22, 165882),
  datetime.datetime(2025, 7, 17, 10, 30, 23, 739566),
  datetime.datetime(2025, 7, 17, 10, 30, 25, 230055),
  datetime.datetime(2025, 7, 17, 10, 30, 26, 824971),
  datetime.datetime(2025, 7, 17, 10, 30, 27, 518078),
  datetime.datetime(2025, 7, 17, 10, 30, 29, 163045),
  datetime.datetime(2025, 7, 17, 10, 30, 30, 729659),
  datetime.datetime(2025, 7, 17, 10, 30, 32, 397573)],
 'airport_code': ['LAX',
  'LAX',
  'JFK',
  'JFK',
  'DEN',
  'DEN',
  'DTW',
  'DTW',
  'ORD',
  'ORD',
  'ATL',
  'ATL'],
 'station_id': [72295,
  72295,
  71845,
  71845,
  72565,
  72565,
  72537,
  72537,
  72530,
  72530,
  72219,
  72219],
 'extracted_data': [{'meta': {'generated': '2025-07-17 08:30:15'},
   'data': [{'time': '2022-12-01 00:00:00',
     'temp': 15.0,
     'dwpt': 9.4,
     'rhum': 69.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 220.0,
     'wspd': 13.0,
     'wpgt': None,
     'pres': 1014.6,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 01:00:00',
     'temp': 14.4,
     'dwpt': 9.4,
     'rhum': 72.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 210.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1014.8,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 02:00:00',
     'temp': 14.4,
     'dwpt': 9.0,
     'rhum': 70.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 210.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1015.1,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 03:00:00',
     'temp': 13.9,
     'dwpt': 8.9,
     'rhum': 72.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 190.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1015.2,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 04:00:00',
     'temp': 14.4,
     'dwpt': 7.7,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 150.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1015.6,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 05:00:00',
     'temp': 13.9,
     'dwpt': 7.2,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 120.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1016.3,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 06:00:00',
     'temp': 13.9,
     'dwpt': 7.2,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 120.0,
     'wspd': 5.4,
     'wpgt': None,
     'pres': 1016.4,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 07:00:00',
     'temp': 13.9,
     'dwpt': 6.7,
     'rhum': 62.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 180.0,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1016.6,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 08:00:00',
     'temp': 13.9,
     'dwpt': 6.0,
     'rhum': 59.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 150.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1015.6,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 09:00:00',
     'temp': 13.9,
     'dwpt': 6.0,
     'rhum': 59.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 150.0,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1015.7,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 10:00:00',
     'temp': 13.9,
     'dwpt': 5.5,
     'rhum': 57.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 120.0,
     'wspd': 5.4,
     'wpgt': None,
     'pres': 1015.6,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 11:00:00',
     'temp': 13.9,
     'dwpt': 5.5,
     'rhum': 57.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 150.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1015.6,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 12:00:00',
     'temp': 13.3,
     'dwpt': 5.7,
     'rhum': 60.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 90.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1015.5,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 13:00:00',
     'temp': 13.3,
     'dwpt': 6.6,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 90.0,
     'wspd': 5.4,
     'wpgt': None,
     'pres': 1015.9,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 14:00:00',
     'temp': 13.3,
     'dwpt': 6.6,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 130.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1016.3,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 15:00:00',
     'temp': 13.3,
     'dwpt': 9.0,
     'rhum': 75.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 170.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1017.0,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-01 16:00:00',
     'temp': 13.9,
     'dwpt': 8.3,
     'rhum': 69.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 100.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1017.5,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 17:00:00',
     'temp': 14.4,
     'dwpt': 8.3,
     'rhum': 67.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 140.0,
     'wspd': 13.0,
     'wpgt': None,
     'pres': 1018.0,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 18:00:00',
     'temp': 14.4,
     'dwpt': 9.0,
     'rhum': 70.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 170.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1018.0,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 19:00:00',
     'temp': 14.4,
     'dwpt': 9.0,
     'rhum': 70.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1017.9,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 20:00:00',
     'temp': 15.0,
     'dwpt': 8.2,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 230.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1017.5,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 21:00:00',
     'temp': 15.6,
     'dwpt': 8.3,
     'rhum': 62.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 230.0,
     'wspd': 20.5,
     'wpgt': None,
     'pres': 1017.1,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 22:00:00',
     'temp': 15.0,
     'dwpt': 7.8,
     'rhum': 62.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 260.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1016.5,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-01 23:00:00',
     'temp': 14.4,
     'dwpt': 7.2,
     'rhum': 62.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 200.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1015.9,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 00:00:00',
     'temp': 14.4,
     'dwpt': 7.7,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 210.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1016.6,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 01:00:00',
     'temp': 13.9,
     'dwpt': 7.9,
     'rhum': 67.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 240.0,
     'wspd': 13.0,
     'wpgt': None,
     'pres': 1016.8,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 02:00:00',
     'temp': 13.9,
     'dwpt': 7.2,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 200.0,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1016.9,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 03:00:00',
     'temp': 13.9,
     'dwpt': 7.9,
     'rhum': 67.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 190.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1017.3,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 04:00:00',
     'temp': 14.4,
     'dwpt': 7.7,
     'rhum': 64.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 220.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1017.9,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 05:00:00',
     'temp': 13.9,
     'dwpt': 7.9,
     'rhum': 67.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 100.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1018.3,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 06:00:00',
     'temp': 13.9,
     'dwpt': 7.9,
     'rhum': 67.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 100.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1018.4,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 07:00:00',
     'temp': 13.9,
     'dwpt': 8.3,
     'rhum': 69.0,
     'prcp': None,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1019.0,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 08:00:00',
     'temp': 12.8,
     'dwpt': 8.9,
     'rhum': 77.0,
     'prcp': None,
     'snow': None,
     'wdir': 110.0,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1018.3,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 09:00:00',
     'temp': 12.8,
     'dwpt': 9.4,
     'rhum': 80.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 90.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1018.4,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 10:00:00',
     'temp': 13.3,
     'dwpt': 9.4,
     'rhum': 77.0,
     'prcp': None,
     'snow': None,
     'wdir': 90.0,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1018.7,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-02 11:00:00',
     'temp': 11.7,
     'dwpt': 10.6,
     'rhum': 93.0,
     'prcp': 0.3,
     'snow': None,
     'wdir': 80.0,
     'wspd': 13.0,
     'wpgt': None,
     'pres': 1018.9,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-02 12:00:00',
     'temp': 11.1,
     'dwpt': 10.6,
     'rhum': 97.0,
     'prcp': 0.3,
     'snow': None,
     'wdir': 80.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1018.7,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-02 13:00:00',
     'temp': 11.7,
     'dwpt': 10.6,
     'rhum': 93.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 70.0,
     'wspd': 16.6,
     'wpgt': None,
     'pres': 1019.0,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-02 14:00:00',
     'temp': 11.7,
     'dwpt': 10.6,
     'rhum': 93.0,
     'prcp': None,
     'snow': None,
     'wdir': 80.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1019.5,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-02 15:00:00',
     'temp': 11.1,
     'dwpt': 10.6,
     'rhum': 97.0,
     'prcp': 0.5,
     'snow': None,
     'wdir': 80.0,
     'wspd': 16.6,
     'wpgt': None,
     'pres': 1020.0,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 16:00:00',
     'temp': 11.7,
     'dwpt': 11.1,
     'rhum': 96.0,
     'prcp': 0.3,
     'snow': None,
     'wdir': 80.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1020.5,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 17:00:00',
     'temp': 12.2,
     'dwpt': 11.1,
     'rhum': 93.0,
     'prcp': 0.5,
     'snow': None,
     'wdir': 80.0,
     'wspd': 16.6,
     'wpgt': None,
     'pres': 1021.0,
     'tsun': None,
     'coco': 5},
    {'time': '2022-12-02 18:00:00',
     'temp': 12.8,
     'dwpt': 11.7,
     'rhum': 93.0,
     'prcp': None,
     'snow': None,
     'wdir': 80.0,
     'wspd': 18.4,
     'wpgt': None,
     'pres': 1021.3,
     'tsun': None,
     'coco': 5},
    {'time': '2022-12-02 19:00:00',
     'temp': 13.3,
     'dwpt': 12.2,
     'rhum': 93.0,
     'prcp': None,
     'snow': None,
     'wdir': 80.0,
     'wspd': 20.5,
     'wpgt': None,
     'pres': 1021.0,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 20:00:00',
     'temp': 14.4,
     'dwpt': 11.7,
     'rhum': 84.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 80.0,
     'wspd': 18.4,
     'wpgt': None,
     'pres': 1020.2,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 21:00:00',
     'temp': 15.6,
     'dwpt': 11.2,
     'rhum': 75.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 110.0,
     'wspd': 31.7,
     'wpgt': None,
     'pres': 1019.2,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 22:00:00',
     'temp': 16.1,
     'dwpt': 10.6,
     'rhum': 70.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 80.0,
     'wspd': 13.0,
     'wpgt': None,
     'pres': 1019.3,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-02 23:00:00',
     'temp': 16.1,
     'dwpt': 10.6,
     'rhum': 70.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 130.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1019.0,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-03 00:00:00',
     'temp': 16.1,
     'dwpt': 10.6,
     'rhum': 70.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 310.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1018.8,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-03 01:00:00',
     'temp': 15.0,
     'dwpt': 11.8,
     'rhum': 81.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 310.0,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1018.8,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-03 02:00:00',
     'temp': 15.0,
     'dwpt': 11.8,
     'rhum': 81.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 320.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1019.0,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-03 03:00:00',
     'temp': 15.0,
     'dwpt': 12.1,
     'rhum': 83.0,
     'prcp': 0.3,
     'snow': None,
     'wdir': 260.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1019.3,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-03 04:00:00',
     'temp': 14.4,
     'dwpt': 12.3,
     'rhum': 87.0,
     'prcp': 1.0,
     'snow': None,
     'wdir': 300.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1019.3,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-03 05:00:00',
     'temp': 14.4,
     'dwpt': 12.8,
     'rhum': 90.0,
     'prcp': None,
     'snow': None,
     'wdir': 300.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1019.6,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-03 06:00:00',
     'temp': 15.0,
     'dwpt': 12.1,
     'rhum': 83.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 310.0,
     'wspd': 5.4,
     'wpgt': None,
     'pres': 1019.4,
     'tsun': None,
     'coco': 7},
    {'time': '2022-12-03 07:00:00',
     'temp': 15.0,
     'dwpt': 12.1,
     'rhum': 83.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 310.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1019.3,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-03 08:00:00',
     'temp': 14.4,
     'dwpt': 12.3,
     'rhum': 87.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 300.0,
     'wspd': 11.2,
     'wpgt': None,
     'pres': 1019.2,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-03 09:00:00',
     'temp': 14.4,
     'dwpt': 12.3,
     'rhum': 87.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 300.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1018.8,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 10:00:00',
     'temp': 13.9,
     'dwpt': 11.8,
     'rhum': 87.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1018.5,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-03 11:00:00',
     'temp': 13.9,
     'dwpt': 12.3,
     'rhum': 90.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 300.0,
     'wspd': 5.4,
     'wpgt': None,
     'pres': 1018.0,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-03 12:00:00',
     'temp': 12.2,
     'dwpt': 11.7,
     'rhum': 97.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1017.7,
     'tsun': None,
     'coco': 4},
    {'time': '2022-12-03 13:00:00',
     'temp': 12.2,
     'dwpt': 11.7,
     'rhum': 97.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1017.9,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 14:00:00',
     'temp': 13.3,
     'dwpt': 11.7,
     'rhum': 90.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 77.0,
     'wspd': 5.4,
     'wpgt': None,
     'pres': 1018.2,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 15:00:00',
     'temp': 12.2,
     'dwpt': 11.1,
     'rhum': 93.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1018.8,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 16:00:00',
     'temp': 13.9,
     'dwpt': 11.8,
     'rhum': 87.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1019.2,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 17:00:00',
     'temp': 16.1,
     'dwpt': 12.3,
     'rhum': 78.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1019.7,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 18:00:00',
     'temp': 17.8,
     'dwpt': 12.7,
     'rhum': 72.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 0.0,
     'wspd': 0.0,
     'wpgt': None,
     'pres': 1019.7,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 19:00:00',
     'temp': 18.9,
     'dwpt': 12.9,
     'rhum': 68.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 240.0,
     'wspd': 5.4,
     'wpgt': None,
     'pres': 1019.3,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-03 20:00:00',
     'temp': 20.0,
     'dwpt': 10.7,
     'rhum': 55.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 240.0,
     'wspd': 7.6,
     'wpgt': None,
     'pres': 1018.2,
     'tsun': None,
     'coco': 2},
    {'time': '2022-12-03 21:00:00',
     'temp': 19.4,
     'dwpt': 11.7,
     'rhum': 61.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 260.0,
     'wspd': 13.0,
     'wpgt': None,
     'pres': 1017.5,
     'tsun': None,
     'coco': 2},
    {'time': '2022-12-03 22:00:00',
     'temp': 18.3,
     'dwpt': 13.4,
     'rhum': 73.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 260.0,
     'wspd': 20.5,
     'wpgt': None,
     'pres': 1017.4,
     'tsun': None,
     'coco': 2},
    {'time': '2022-12-03 23:00:00',
     'temp': 17.8,
     'dwpt': 13.3,
     'rhum': 75.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 260.0,
     'wspd': 18.4,
     'wpgt': None,
     'pres': 1017.4,
     'tsun': None,
     'coco': 2},
    {'time': '2022-12-04 00:00:00',
     'temp': 17.2,
     'dwpt': 13.9,
     'rhum': 81.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 270.0,
     'wspd': 17.0,
     'wpgt': None,
     'pres': 1017.7,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-04 01:00:00',
     'temp': 16.1,
     'dwpt': 13.9,
     'rhum': 87.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 270.0,
     'wspd': 16.6,
     'wpgt': None,
     'pres': 1018.1,
     'tsun': None,
     'coco': 2},
    {'time': '2022-12-04 02:00:00',
     'temp': 15.6,
     'dwpt': 14.5,
     'rhum': 93.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 250.0,
     'wspd': 9.4,
     'wpgt': None,
     'pres': 1018.5,
     'tsun': None,
     'coco': 2},
    {'time': '2022-12-04 03:00:00',
     'temp': 15.6,
     'dwpt': 14.5,
     'rhum': 93.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 270.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1018.8,
     'tsun': None,
     'coco': 2},
    {'time': '2022-12-04 04:00:00',
     'temp': 15.6,
     'dwpt': 14.5,
     'rhum': 93.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 240.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1018.8,
     'tsun': None,
     'coco': 3},
    {'time': '2022-12-04 05:00:00',
     'temp': 15.6,
     'dwpt': 14.5,
     'rhum': 93.0,
     'prcp': 0.0,
     'snow': None,
     'wdir': 250.0,
     'wspd': 14.8,
     'wpgt': None,
     'pres': 1019.0,
     'tsun': None,
     'coco': 3},

In [23]:
weather_hourly_df = pd.DataFrame(weather_hourly_dict)
weather_hourly_df

,extracted_at,airport_code,station_id,extracted_data
0,2025-07-17 10:30:15.617482,LAX,72295,"{'meta': {'generated': '2025-07-17 08:30:15'},..."
1,2025-07-17 10:30:17.367580,LAX,72295,"{'meta': {'generated': '2025-07-17 08:30:17'},..."
2,2025-07-17 10:30:18.935360,JFK,71845,"{'meta': {'generated': '2025-07-17 08:30:18'},..."
3,2025-07-17 10:30:20.520268,JFK,71845,"{'meta': {'generated': '2025-07-17 08:30:20'},..."
4,2025-07-17 10:30:22.165882,DEN,72565,"{'meta': {'generated': '2025-07-17 08:30:22'},..."
5,2025-07-17 10:30:23.739566,DEN,72565,"{'meta': {'generated': '2025-07-17 08:30:23'},..."
6,2025-07-17 10:30:25.230055,DTW,72537,"{'meta': {'generated': '2025-07-17 08:30:25'},..."
7,2025-07-17 10:30:26.824971,DTW,72537,"{'meta': {'generated': '2025-07-17 08:30:26'},..."
8,2025-07-17 10:30:27.518078,ORD,72530,"{'meta': {'generated': '2025-07-17 08:30:27'},..."
9,2025-07-17 10:30:29.163045,ORD,72530,"{'meta': {'generated': '2025-07-17 08:30:29'},..."
10,2025-07-17 10:30:30.729659,ATL,72219,"{'meta': {'generated': '2025-07-17 08:30:30'},..."
11,2025-07-17 10:30:32.397573,ATL,72219,"{'meta': {'generated': '2025-07-17 08:30:32'},..."

In [24]:
df_JFK_jan24 = pd.json_normalize(pd.json_normalize(weather_hourly_df['extracted_data']).loc[0, 'data'])
df_JFK_jan24

,time,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco
0,2022-12-01 00:00:00,15.0,9.4,69.0,0.0,None,220.0,13.0,None,1014.6,None,3
1,2022-12-01 01:00:00,14.4,9.4,72.0,0.0,None,210.0,9.4,None,1014.8,None,3
2,2022-12-01 02:00:00,14.4,9.0,70.0,0.0,None,210.0,7.6,None,1015.1,None,3
3,2022-12-01 03:00:00,13.9,8.9,72.0,0.0,None,190.0,7.6,None,1015.2,None,3
4,2022-12-01 04:00:00,14.4,7.7,64.0,0.0,None,150.0,9.4,None,1015.6,None,3
...,...,...,...,...,...,...,...,...,...,...,...,...
739,2022-12-31 19:00:00,15.6,14.5,93.0,NaN,None,230.0,16.6,None,1017.1,None,4
740,2022-12-31 20:00:00,15.6,14.5,93.0,NaN,None,230.0,14.8,None,1016.2,None,4
741,2022-12-31 21:00:00,15.0,14.4,96.0,NaN,None,220.0,16.6,None,1015.0,None,4
742,2022-12-31 22:00:00,15.0,13.9,93.0,NaN,None,200.0,18.4,None,1014.3,None,8
743,2022-12-31 23:00:00,15.0,13.9,93.0,0.0,None,200.0,22.3,None,1014.0,None,8

Ingesting Data in to DB

In [25]:
# getting API and DB credentials - Alternative 1: dotenv_values()

config = dotenv_values()
 
pg_user = config['POSTGRES_USER'] # align the key labels with your .env file
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']

In [26]:
# updating the url
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

# creating the engine
engine = create_engine(url, echo=False)

In [27]:
# defining data types for the DB
dtype_dict = {
    'extracted_at':types.DateTime,
    'airport_code': types.String,
    'station_id': types.Integer,
    'extracted_data':postgres_json
             }

In [28]:
weather_hourly_df.to_sql(name = 'weather_hourly_raw', 
                       con = engine, 
                       schema = pg_schema, # pandas is allowing to specify, in which schema the table shall be created
                       if_exists='replace', 
                       dtype=dtype_dict,
                       index=False
                      )

12